" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_awesome

source ~/.vim_awesome/general.vim
source ~/.vim_awesome/plugins.vim
source ~/.vim_awesome/functions.vim
source ~/.vim_awesome/filetypes.vim
source ~/.vim_awesome/general-mappings.vim
source ~/.vim_awesome/plugins-mappings.vim
source ~/.vim_awesome/filetypes-mappings.vim
source ~/.vim_awesome/plugins-color-theme.vim

try
  source ~/.vim_awesome/custom.vim
catch
endtry
